# Generated by Django 5.1.7 on 2025-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userrsakey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
